name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:     

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: Shane-Dias
          output: dist/snake.svg

      - name: Commit and push the animation
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Updated snake animation"
          git push
