name: Generate Snake Animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir -p dist # Create dist directory if it doesn't exist

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg # Specify the output path explicitly

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist # Ensure this matches where the file is generated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
